- use try-reload-or-restart - fix ordering for fail2ban

diff --git a/zypper_ps_restart b/zypper_ps_restart
--- a/zypper_ps_restart
+++ b/zypper_ps_restart
@@ -126,18 +126,18 @@ if [ -x "$ZYPPER" ]; then # >SLES10 SP2
 					'firewalld')
 					  if systemctl -q is-enabled fail2ban ; then
 						LOG "Restarting services firewalld and fail2ban"
-						systemctl stop firewalld
 						systemctl stop fail2ban
+						systemctl stop firewalld
 						systemctl start firewalld
 						systemctl start fail2ban
 					  else
 						LOG "Restarting firewalld"
-						systemctl restart firewalld
+						systemctl try-reload-or-restart firewalld
 					  fi
 				  ;;
 				  *)
 					LOG "Restarting $service"
-					systemctl try-restart $service.service || LOG "$service restart failed" >&2; 
+					systemctl try-reload-or-restart $service.service || LOG "$service restart failed" >&2; 
 				  ;;
 				esac
 			  fi
